# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6uD9Wa05qiONHfnmf9AVnFQCL3mbDCJ
"""

import numpy as np
import matplotlib.pyplot as plt

# Создаем данные
x = np.linspace(0, 10, 100)  # 100 точек от 0 до 10
y = np.sin(x)

# Строим график
plt.plot(x, y, label='sin(x)')

# Добавляем подписи и сетку
plt.xlabel('x')
plt.ylabel('y')
plt.title('График функции синус')
plt.grid(True)
plt.legend()

# Отображаем график
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Создаем случайные данные
np.random.seed(42)  # Фиксируем seed для воспроизводимости
x = np.random.rand(100)
y = np.random.rand(100)

# Строим график
plt.scatter(x, y, label='Случайные точки')

# Добавляем подписи и сетку
plt.xlabel('x')
plt.ylabel('y')
plt.title('График рассеяния случайных точек')
plt.grid(True)
plt.legend()

# Отображаем график
plt.show()